Fix build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,7 +44,7 @@ jobs:
       - name: Lint build script
         run: |
           sudo apt-get update && sudo apt-get install -y shellcheck
-          shellcheck build.sh || { echo "Shellcheck failed"; exit 1; }
+          shellcheck **/*.sh || { echo "Shellcheck failed"; exit 1; }
 
       # Generate additional build tags
       - name: Generate tags
@@ -139,15 +139,20 @@ jobs:
             echo "digest=$(podman inspect ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }}:${tag} --format '{{.Digest}}')" >> $GITHUB_OUTPUT
           done
 
-      # # Sign container
-      # - uses: sigstore/cosign-installer@v3.8.2
-      # - name: Sign container image
-      #   shell: bash
-      #   run: |
-      #     cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}@${{ steps.push.outputs.digest }}
-      #   env:
-      #     COSIGN_EXPERIMENTAL: false
-      #     COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
+      # Sign container
+      - uses: sigstore/cosign-installer@v3.8.2
+
+      - name: Write signing key to disk
+        run: echo "${{ secrets.SIGNING_SECRET }}" > cosign.key
+
+      - name: Sign container image
+        shell: bash
+        run: |
+          cosign sign -y --key cosign.key \
+          ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}@${{ steps.push.outputs.digest }}
+        env:
+          COSIGN_EXPERIMENTAL: false
+          COSIGN_PASSWORD: ""
 
       # Clean up buildah/podman images and containers
       - name: Cleanup
